### ISSUE TITLE
Hold count over MQTT?

### ISSUE THREAD

**Issue by peci1** [hardwario/twr-radio-push-button#3]
I've seen version 1.4.0 added support for detecting button hold event. How do I get this event over MQTT via gateway?

According to https://github.com/bigclownlabs/bcf-gateway/blob/b5e71d6f1e73dfb4a88b35c9b7272cf0afa754b8/app/application.c#L205 , there should be event `node/push-button-tv/push-button/-/hold-count`. But I don't see it. Not even when I run `mosquitto_sub -t 'node/#'`

I can normally see the button clicks, thermometer, battery and orientation changes from this module.

`node/push-button-tv/info {"firmware": "push-button", "version": "v1.4.1", "mode": 3}`

**Comment by blavka** [comment]
Hello,
so sorry no one responded, I didn't receive an issue email.
The firmware for dongle needs to be updated to the latest version.

bigclownlabs/bcf-gateway-usb-dongle:v1.13.0

**Comment by peci1** [comment]
Thanks. This is weird. I'm pretty sure I've updated the gateway to 1.13 a few days ago because of problems with the relay module. I even physically re-plugged it. Today I did the firmware upgrade to 1.13 for the second time (just to prove in this issue it doesn't work), and now the hold count works...

**Comment by blavka** [comment]
Magic :D
